<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>comment</key>
	<string>Opal Syntax: 0.1</string>
	<key>fileTypes</key>
	<array>
		<string>opal</string>
		<string>Opalfile</string>
	</array>
	<key>name</key>
	<string>Opal</string>
	<key>scopeName</key>
	<string>source.opal</string>
	<key>patterns</key>
	<array>
	     <dict>
         <key>captures</key>
         <dict>
           <key>1</key>
           <dict>
             <key>name</key>
             <string>keyword.control.interface.opal</string>
           </dict>
           <key>2</key>
           <dict>
             <key>name</key>
             <string>entity.name.type.interface.opal</string>
           </dict>
           <key>4</key>
   				<dict>
   					<key>name</key>
   					<string>entity.other.inherited-class.opal</string>
   				</dict>
   				<key>5</key>
   				<dict>
   					<key>name</key>
   					<string>punctuation.separator.inheritance.opal</string>
   				</dict>
   				<key>6</key>
   				<dict>
   					<key>name</key>
   					<string>variable.other.object.opal</string>
   				</dict>
   				<key>7</key>
   				<dict>
   					<key>name</key>
   					<string>punctuation.definition.variable.opal</string>
   				</dict>
         </dict>
         <key>match</key>
    <string>^\s*(interface)\s+(([.a-zA-Z0-9_:@]+(\s*(&lt;)\s*[.a-zA-Z0-9_:]+)?)|((&lt;&lt;)\s*[.a-zA-Z0-9_:]+))</string>
       <key>name</key>
       <string>meta.interface.opal</string>
       </dict>
    <dict>
      <key>captures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>keyword.control.class.opal</string>
        </dict>
        <key>2</key>
        <dict>
          <key>name</key>
          <string>entity.name.type.class.opal</string>
        </dict>
        <key>4</key>
				<dict>
					<key>name</key>
					<string>entity.other.inherited-class.opal</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.inheritance.opal</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>variable.other.object.opal</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.variable.opal</string>
				</dict>
      </dict>
      <key>match</key>
 <string>^\s*(class)\s+(([.a-zA-Z0-9_:]+(\s*(&lt;)\s*[.a-zA-Z0-9_:]+)?)|((&lt;&lt;)\s*[.a-zA-Z0-9_:]+))</string>
    <key>name</key>
    <string>meta.class.opal</string>
    </dict>
	 <dict>
	   <key>captures</key>
	   <dict>
	     <key>1</key>
	     <dict>
	       <key>name</key>
	       <string>punctuation.definition.comment.opal</string>
	     </dict>
	   </dict>
	   <key>match</key>
	   <string>(#).*$\n?</string>
	   <key>name</key>
	   <string>comment.line.opal</string>
	 </dict>
	 <dict>
	   <key>name</key>
	   <string>keyword.control.opal</string>
	   <key>match</key>
 <string>(?&lt;!\.)\b(try|case|class|interface|implementation|else|end|finally|for|if|in|try|catch|then|unless|until|return|when|while|switch|def|function|do|typeof|instanceof|throw)\b(?![?!])</string>
	 </dict>
	 <dict>
	   <key>comment</key>
	   <string>Like above keywords, but logical ops, and dont need end</string>
	   <key>name</key>
	   <string>keyword.operator.logical.opal</string>
	   <key>match</key>
	   <string>(?&lt;!\.)\b(and|not|or)\b</string>
	 </dict>
	 <dict>
	   <key>name</key>
	   <string>constant.language.opal</string>
	   <key>match</key>
	   <string>\b(null|undefined|true|false|this|self|super|nil)\b(?![?!])</string>
	 </dict>
	 <dict>
	   <key>name</key>
	   <string>keyword.other.special-method.opal</string>
	   <key>match</key>
	   <string>\b(new|initialize|apply|call|prototype|constructor|length|print|require|module|system|exports|process|console|log|global)\b</string>
	 </dict>
	 <dict>
 	   <key>name</key>
 	   <string>keyword.other.special-method.opal</string>
 	   <key>match</key>
 	   <string>\b(function|object|number|defined|string)\?</string>
 	 </dict>
	 <dict>
	   <key>name</key>
	   <string>variable.other.constant.opal</string>
	   <key>match</key>
	   <string>\b[A-Z]\w*\b</string>
	 </dict>
	 <dict>
	   <key>name</key>
	   <string>keyword.operator.comparison.opal</string>
	   <key>match</key>
 <string>&lt;=&gt;|&lt;(?!&lt;|=)|&gt;(?!&lt;|=|&gt;)|&lt;=|&gt;=|===|==|=~|!=|!~|\bis\b|\bisnt\b|(?&lt;=[ \t])\?</string>
	 </dict>
	 <dict>
	   <key>name</key>
	   <string>keyword.operator.arithmetic.opal</string>
	   <key>match</key>
	   <string>(%|&amp;|\*\*|\*|\+|\-|/)</string>
	 </dict>
	 <dict>
	   <key>name</key>
	   <string>keyword.operator.assignment.opal</string>
	   <key>match</key>
	   <string>=</string>
	 </dict>
	 <dict>
	   <key>name</key>
	   <string>variable.other.readwrite.instance.opal</string>
	   <key>match</key>
	   <string>(@)[a-zA-Z_$]\w*</string>
	   <key>captures</key>
	   <dict>
	     <key>1</key>
	     <dict>
	       <key>name</key>
	       <string>punctuation.definition.variable.opal</string>
	     </dict>
	   </dict>
	 </dict>
	 <dict>
 	   <key>name</key>
 	   <string>variable.other.readwrite.class.opal</string>
 	   <key>match</key>
 	   <string>(@@)[a-zA-Z_$]\w*</string>
 	   <key>captures</key>
 	   <dict>
 	     <key>1</key>
 	     <dict>
 	       <key>name</key>
 	       <string>punctuation.definition.variable.opal</string>
 	     </dict>
 	   </dict>
 	 </dict>
	 <dict>
			<key>begin</key>
			<string>'</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.opal</string>
				</dict>
			</dict>
			<key>end</key>
			<string>'</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.opal</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.single.opal</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\'|\\\\</string>
					<key>name</key>
					<string>constant.character.escape.opal</string>
				</dict>
			</array>
		</dict>
		<dict>
  		<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.opal</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.opal</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.single.opal</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\"|\\\\</string>
					<key>name</key>
					<string>constant.character.escape.opal</string>
				</dict>
			</array>
  	</dict>
  	<dict>
			<key>match</key>
			<string>:</string>
			<key>name</key>
			<string>punctuation.separator.other.opal</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\;</string>
			<key>name</key>
			<string>punctuation.separator.statement.opal</string>
		</dict>
		<dict>
			<key>match</key>
			<string>,</string>
			<key>name</key>
			<string>punctuation.separator.object.opal</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\.|::</string>
			<key>name</key>
			<string>punctuation.separator.method.opal</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\{|\}</string>
			<key>name</key>
			<string>punctuation.section.scope.opal</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\[|\]</string>
			<key>name</key>
			<string>punctuation.section.array.opal</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\(|\)</string>
			<key>name</key>
			<string>punctuation.section.function.opal</string>
		</dict>
		<dict>
			<key>match</key>
					<string>\b((0(x|X)[0-9a-fA-F]+)|([0-9_]+(\.[0-9_]+)?(e[+\-]?[0-9]+)?))\b</string>
			<key>name</key>
			<string>constant.numeric.opal</string>
		</dict>
		<dict>
       <key>captures</key>
       <dict>
         <key>1</key>
         <dict>
           <key>name</key>
           <string>keyword.control.def.opal</string>
         </dict>
         <key>2</key>
         <dict>
           <key>name</key>
           <string>entity.name.function.opal</string>
         </dict>
         <key>3</key>
 				<dict>
 					<key>name</key>
 					<string>entity.name.function.opal</string>
 				</dict>
       </dict>
       <key>match</key>
       <string>^\s*(def)\s+([a-zA-Z_]+)</string>
  <!-- <string>^\s*(def)\s+(([.a-zA-Z0-9_:@]+(\s*(&lt;)\s*[.a-zA-Z0-9_:]+)?))</string> -->
     <key>name</key>
     <string>meta.function.opal</string>
     </dict>
	</array>
	<key>uuid</key>
	<string>A46E1083-F1AC-405B-8F92-37FF385F58D2</string>
</dict>
</plist>
